# Force Node.js provider
providers = ["node"]

# Install dependencies
[phases.install]
dependsOn = ["setup"]
cmds = ["npm ci"]

# Build
[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]

# Start
[start]
cmd = "node dist/main.js"
